{% set name = "hunspell" %}
{% set version = "1.6.2" %}
{% set sha256 = "3cd9ceb062fe5814f668e4f22b2fa6e3ba0b339b921739541ce180cac4d6f4c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/hunspell/hunspell/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  has_prefix_files:
    - bin/hunspell

requirements:
  build:
    - toolchain3
    - autoconf
    - automake
    - libtool
    - make
    - gettext
    - readline 6.2*
  run:
    - gettext
    - readline 6.2*

test:
  commands:
    - hunspell --help

about:
  home: http://hunspell.github.io/
  license: MPL 1.1/GPL 2.0/LGPL 2.1
  license_family: GPL
  license_file: COPYING
  summary: 'The most popular spellchecking library.'
  description: |
    Hunspell is the spell checker of LibreOffice, OpenOffice.org, Mozilla Firefox 3 & Thunderbird,
    Google Chrome, and it is also used by proprietary software packages, like macOS, InDesign,
    memoQ, Opera and SDL Trados.
  doc_url: http://hunspell.github.io/
  dev_url: https://github.com/hunspell/hunspell

extra:
  recipe-maintainers:
    - scopatz
    - asmeurer
