travis:
  secure:
    BINSTAR_TOKEN: qbdF0AFqZWpbRCvSX+5FgNuArZbNMdMap3ikNqKQ9MloMJqch/oUYS96MANj2EAfuVAo6w8XY9bWwNt2mfQwbZSSzp7P1KYnj/0cxeTl3sSCYz2cs5YjEr7xDE4QN3Oc0UNIYX+Le8di1YGlkgM6K/k4WIiAsYOdfJlLKDiFWLg6YI1idom66lAJxRJJtYZHf5TqRbcaiToAdENP4Lf/8zim9gzrH8xzF0Pj0RY2mBX8i4Nhd05L3KbMnXOcfS53jqwjSZDPm2BlqnIF49vaPaRSrLLu6i8A7hUHfjYedVENC5ZRt+ONHzNY9mNylIZJRKu6CmFnrrb7EF5IO43+hTfPrKILMzf2F35V2juefbndt7l00jo0P9RDmT45+8XvSf07heC/JUJO+GwOdc0Umycj42Gng/n9vWbKCUGZQN8YUcutaTY3n2apmw9TllhVhgUDO6VfeMqi4OrCGEojeMK5Pyi7NQ2SCnmEhQeIHmjx3mY4tE8kVrBPk+okb10fN943zYnhun75kB6WA46IOlFWcLyTEAm1rgekpLIgyfAkYRgET5/vyQypN/79bwaDT3Hkl8x8Q2Dar2EOgbLc7sOdJstRGiTbtpk/9psiKpjUaXAd8CCpjov9TNTthzRaQP6uNNAXdSipZbrjj1imhbOJwqxPLaOvUgMk7IyA2so=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
