appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tfOKz5LtFTUCZoHddUyPdC1RAOaCWEAU8YtJqslSbn0S+m4+SO3BHAYfacBkyWQE5Do02De9a2BV0I7WS/yBVULTOgjAHu1Rnz0gnpQmBEivClem9TAaFUJdYPW0nvM2jsYgCYd9XaGfj9kx58aI232aXy/bftwoibUuclA1mmU9UfcX335OEqEoQY3rnhRH6GuXlWhrY+bgx4vf1/S0pcw1BnDiirkLkQq36+z8REQEBtTup9TpxN8rCGEaGS3ZF5JK/ax1SMK2lFA1qWFvrNcP02ZYumWHWDyQWmTcTp+Oh6ludUadYQ75LgxbetfbCJuQisGZeEYoWsgf+eUeepx+JLbZMH8P6lnNH5T+ZTP/RWU/+aVne+PEvgwvszXucExXN5yqW8RaMACSjIRnDEbZsXtjW5IMJkbUhimsItAgPr5URs7/mrefa6Vm6Bzw01A0/vD2npdgPNj/P1Yu0LGi4/f4kVzXgfmfujfTkauzY/r9xuOmRrpF6EsbU0HoeByUauxKNymXqcLRBmRA7hO408CeyTBt/PgzNZ4AP5HzAbXl+hWJ+pVL+zwMtzDrDY5ZYbqjSs49CD/LmIxNDQSFQ3FqamEur9PLztxK8V7bpPU05daCiA0HAEXlrUV2y26UiZgUW0CMbGE2Qdk3M7Y2BC0cLahwtgKjaCSeJ44=}
conda_forge_output_validation: true
